const actionTypes = {
  "FETCH_MOVIES_LOADING": "FETCH_MOVIES_LOADING",
  "FETCH_MOVIES_SUCESS": "FETCH_MOVIES_SUCESS",
  "FETCH_MOVIES_ERROR": "FETCH_MOVIES_ERROR",
  "SEARCH_MOVIES_LOADING": "SEARCH_MOVIES_LOADING",
  "SEARCH_MOVIES_SUCESS": "SEARCH_MOVIES_SUCESS",
  "SEARCH_MOVIES_ERROR": "SEARCH_MOVIES_ERROR",
  "SORT_MOVIES_LOADING": "SORT_MOVIES_LOADING",
  "SORT_MOVIES_SUCESS": "SORT_MOVIES_SUCESS",
  "SORT_MOVIES_ERROR": "SORT_MOVIES_ERROR"
}

export default actionTypes;
