const actionTypes = {
  "FETCH_MOVIES_LOADING": "FETCH_MOVIES_LOADING",
  "FETCH_MOVIES_SUCCESS": "FETCH_MOVIES_SUCCESS",
  "FETCH_MOVIES_ERROR": "FETCH_MOVIES_ERROR",
  "SEARCH_MOVIES": "SEARCH_MOVIES",
  "SORT_MOVIES_BY_BUDGET": "SORT_MOVIES_BY_BUDGET",
  "SORT_MOVIES_BY_YEAR": "SORT_MOVIES_BY_YEAR",
  "FILTER_GENRE": "FILTER_GENRE",
  "FILTER_MOVIES_BY_GENRE": "FILTER_MOVIES_BY_GENRE"
}

export default actionTypes;
