const actionTypes = {
  "FETCH_MOVIES_LOADING": "FETCH_MOVIES_LOADING",
  "FETCH_MOVIES_SUCCESS": "FETCH_MOVIES_SUCCESS",
  "FETCH_MOVIES_ERROR": "FETCH_MOVIES_ERROR",
  "SEARCH_MOVIES": "SEARCH_MOVIES",
  "SORT_MOVIES": "SORT_MOVIES",
}

export default actionTypes;
